In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from pandas import DataFrame, Series

In [4]:
data = DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

In [5]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [6]:
data[1:]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [7]:
data['one'][data['three']>6]

Utah         8
New York    12
Name: one, dtype: int32

In [8]:
data = np.array([1,3,5,7,9])

In [9]:
DataFrame(data)

   0
0  1
1  3
2  5
3  7
4  9

In [15]:
def file2frame(filename):
    fr = open(filename, 'rt', encoding='utf-8')
    data_list = [line.strip() for line in fr.readlines()]
    return DataFrame(data_list)

In [16]:
file2frame('./data/meidi_jd.txt')

                                                       0
0                               京东商城信得过，买的放心，用的省心、安心、放心！
1                        给公司宿舍买的，上门安装很快，快递也送的及时，不错的。给五分吧
2                                            美的值得信赖，质量不错
3                               不错不错的哦，第一次在京东买这些产品，感觉相当好
4                                  很满意，水方一晚上都还是热的早上还能再洗，
5                            自己动手安装的，买材料发了不到50块钱，自我感觉良好！
6                                            几套出租房一直用这款。
7                                    还不错，就是快递有点慢，不打电话都不送
8                             东西很不错 双十一抢的 物美价廉  值得购买 赞一个
9                                          性价比高！下次还会光顾的！
10     前天晚上定货，第二天早上就送货，下午马上就安装，速度超快。送货员态度很好，安装师傅也很好，免...
11                                                   还好吧
12                                       应该值得信任的品牌。。。。。。
13                                           价格便宜，购物方便快捷
14                                很好很好很好很好很好很好很好很好很好很好很好
15     的(Midea) F40-15A1 40升 电热水器 .的(Midea) F40-15A1 ...
16                                       帮同事买的他说不错，送货到家！
17                                     用了一段时间了，好用，没什么问题！
18                              怎么这样，前天买的，今天到货，价格却便宜了50元
19                        很好用，很方便！第二次购买了&hellip;&hellip;
20                                          给公司买的，就是方便而已
21                2个人洗澡的水还可以，再多就最好用大一些的容量。自己没有选好，产品还是不错。
22                               挺好的    ，为什么还非得写十个字以上？\n
23     明年准备装修 热水器突然坏了 换个好的不值当 ，就买了个便宜的凑合先用着，师傅不错，原来热水...
24                              999，很给力~~自己加装一个定时器，完美了！！
25                                           大品牌不错。。。。。。
26                                    虽然安装不及时，不过服务倒还是挺好。
27                               按照原定时间准时到货，等待装修结束师傅上门安装
28                               等安装师傅好几天都没来，自己装的，不错，建议买
29                                   我是给家里面人买的，家里父母用着很好用
...                                                  ...
55744                                   值得推荐购买的好东东，性价比较高
55745                                   加热快，出水温度稳定，价格实惠。
55746                                           还行吧，挺喜欢的
55747                                    很实用，水温稳定，出水效率高。
55748  安装热水器包装箱内的零件都要收30元，对美的很失望，投诉总部也没有回复，这种服务质量，以后出...
55749  安装部分太垃圾了！我在承重墙上装热水器，安装人员告诉我不买他们的安装支架就不给装！网上35块...
55750                       出水速度还是比较慢，全胆加热30分钟才热，灯闪的太难受了
55751  烧到65度关掉电源、进水阀，静置10小时就剩下50度了，环境温度大概27度左右。这样的节能水...
55752      物流上门给了20元，不让开箱检查，安装后没有打扫灰尘，没有讲解，还有上门安装费用，不建议买
55753                      烧水速度稍微有点慢。温度不够的时候那个屏幕不停的闪有点闹心
55754                           给父母买的，父母很满意，正好配家里新装修的房子。
55755                                       挺实惠的，发货速度很快。
55756            包装挺好的，服务态度也好。这次订了4台，是给客户定的。好用，下次还得多订几台。
55757  商品还是比错的，就是包装太破了，底部都快磨漏了，塑料都磨掉了，不过检查商品还是没什么问题。再...
55758                   家人说很好，够一家人洗澡。方便又智能，不错支持京东，信赖美的~！
55759                                用了一个星期、暂时没发现什么问题、好~
55760                                             水温不太稳定
55761                               还行 比较满意 其实预约洗澡什么的不实用
55762                       还行  我现在不起火   没怎么用呢  但是送货速度挺快
55763                             最后花了1487元。没发现什么问题。还行吧。
55764                       优点不说了 缺点是按键有些涩 显示器数字一直跳 看得眼晕
55765  这款机子价格倒合适，但是安装费就花了我413元，我一个机子才多少钱啊，这安装费也太暴利了，一...
55766  加热速度快，安装费129元感觉比较合理，保温性能不错加热到60度，12小时后49度，24小时...
55767                                          安装材料感觉像正品
55768                                      热水器还可以，送货比较快。
55769                               还没用使用，感觉很不错。送货师傅人很好，
55770     就是美的安装人员安都没安完  混水阀没安 跟我说 原配那个太丑了 建议自己去买个新的 好看的
55771    用的不错挺好的。安装师傅也很好。提醒亲们，自己提前预约品牌客服安装，京东不管！省得耽误一天时间
55772                                       东西是送朋友的 说挺好的
55773                                       价格便宜 不错 是正品！

[55774 rows x 1 columns]